version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend/4413_project
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      VITE_HOST: localhost
      VITE_PORT: 5000
    networks:
     - network
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend_c
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=ecommerce
      - PORT=5000
      - JWT_SECRET=jwtSecret
      - JWT_LIFETIME=1d
      - NODE_ENV=production
    depends_on:
      - db
  
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

networks:
  network:
volumes:
  db_data:
